Process Process-3430:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yaroslav/Yaroslavus_GitHub/Manticore_1.3/manticore_preprocessing.py", line 429, in create_summary_file_for_tail
    i in range(tail_max_min_list[1] + 1 - tail_max_min_list[0])]
TypeError: 'int' object is not subscriptable
Process Process-3431:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yaroslav/Yaroslavus_GitHub/Manticore_1.3/manticore_preprocessing.py", line 429, in create_summary_file_for_tail
    i in range(tail_max_min_list[1] + 1 - tail_max_min_list[0])]
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "manticore_main_fast.py", line 32, in <module>
    manticore_multiprocessing.fill_the_summary_files_mult(TOTAL_DICT_OF_DAYS, START_TIME)
  File "/home/yaroslav/Yaroslavus_GitHub/Manticore_1.3/manticore_multiprocessing.py", line 170, in fill_the_summary_files_mult
    args=(chunk_to_process[i], mm_chunk_to_process[i], start_time,
IndexError: list index out of range
